name: Daily KPI Report

on:
  schedule:
    - cron: "0 8 * * *" 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  daily-kpi-report:
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get yesterday's date
        id: get_date
        run: |
          YESTERDAY=$(date -u -d "yesterday" "+%d-%m-%y")
          echo "date=$YESTERDAY" >> $GITHUB_OUTPUT

      - name: Generate KPI report for SEND
        run: |
          python3 -m scripts.kpi_report "${{ steps.get_date.outputs.date }}" product=SEND report=pdf slack=true

      - name: Generate KPI report for INTEROP
        run: |
          python3 -m scripts.kpi_report "${{ steps.get_date.outputs.date }}" product=INTEROP report=pdf slack=true

      - name: Upload reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: kpi-reports-${{ steps.get_date.outputs.date }}
          path: reports/
