name: Open alarm duration report

on:
  workflow_dispatch:
    inputs:
      days_back:
        description: "Number of past days to include"
        required: false
        default: "3"

      reports:
        description: "Report formats: html, pdf, csv, json (default: html)"
        required: false
        default: "html,pdf"

permissions:
  contents: read

jobs:
  run-open-duration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run open alarm duration report
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL_SEND: ${{ secrets.SLACK_CHANNEL_SEND }}
          SLACK_CHANNEL_INTEROP: ${{ secrets.SLACK_CHANNEL_INTEROP }}
        run: |
          python3 -m scripts.open_duration ${{ inputs.days_back }} report=${{ inputs.reports }}

      - name: Upload report as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
            name: duration-report-${{ inputs.days_back }}
            path: reports/
